- name: Install Docker
  hosts: server
  become: yes

  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist
      become: true

    - name: Install required dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Remove old Docker repo file (if it exists)
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Remove old Docker key file (if it exists)
      file:
        path: /etc/apt/keyrings/docker.asc
        state: absent

    - name: Create directory for GPG keys if not exists
      file:
        path: /etc/apt/keyrings/
        state: directory
        mode: '0755'

    - name: Download and add Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    - name: Ensure correct permissions for Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add Docker repository with correct Signed-By option
      shell: echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker from official repository
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Download latest docker-compose binary (optional)
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Add user to docker group (optional)
      user:
        name: debydevops
        groups:
          - docker 
        append: yes 
